volumes:
  mariadb_data:

services:
  database:
    image: mariadb:latest
    container_name: fgonboar_db
    volumes:
      - ${PWD}/.mariadb_data:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: fgonboard
      MYSQL_USER: fgonboard
      MYSQL_PASSWORD: fgonboard
      MYSQL_PORT: 3306
